#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# --------------------------------------------------------------------------
# STAGES : raccordement du stockage de photos Supabase pour BlediGo.
#
# CE QUE CET ASSISTANT NE FAIT PAS, ET POURQUOI. Il ne vous demande JAMAIS la
# cle `service_role`, et n ecrit aucun secret sur le disque. Cette cle contourne
# toute la securite au niveau des lignes : c est le secret le plus puissant du
# projet Supabase. Vous la copiez de Supabase vers Render directement, sans
# qu elle transite par un script, un fichier .env ou un presse-papier de plus
# que necessaire.
#
# Le developpement local n en a pas besoin : sans ces variables l API demarre en
# mode simule et rend des images de substitution. C est voulu.
# --------------------------------------------------------------------------

TOTAL_STAGES=5

banner "BlediGo — raccorder le stockage des photos"

# ---------------------------------------------------------------- 1. bucket
stage "Supabase : creer le bucket"
say "Les photos seront stockees chez Supabase, sur le MEME projet que la base."
say "Il n y a donc ni compte a creer, ni service a payer."
open_url "https://supabase.com/dashboard/project/_/storage/buckets"
step "Choisissez votre projet BlediGo si le tableau de bord vous le demande."
step "Cliquez « New bucket »."
step "Nom : medias   (exactement, en minuscules)"
step "Cochez « Public bucket » : les photos d annonces doivent etre lisibles"
say  "  par les visiteurs sans authentification."
step "Creez le bucket."
warn "Un bucket PRIVE ferait echouer l affichage des photos, pas leur envoi :"
note "  la panne apparaitrait plus tard et ailleurs, donc difficile a relier."
pause "Bucket medias cree et public ?"

# ------------------------------------------------------------- 2. URL projet
stage "Supabase : URL du projet"
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Section « Project URL », copiez l URL."
note "  Elle ressemble a https://abcdefghijk.supabase.co"
note "  Ce n est pas un secret : elle apparait deja dans les URL des photos."
ask SUPABASE_URL "Collez l URL du projet :"
if [[ -z "${SUPABASE_URL}" ]]; then
  warn "Aucune URL saisie : vous devrez la reporter vous-meme dans Render."
fi

# ------------------------------------------------------------------ 3. cle
stage "Supabase : cle service_role"
say "Restez sur cette page. Ne collez PAS la cle ici."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Section « Project API keys », ligne « service_role »."
step "Cliquez « Reveal », puis copiez la cle."
warn "Cette cle contourne toute la securite au niveau des lignes."
note "  Elle ne doit jamais etre commitee, ni collee dans un fichier local, ni"
note "  envoyee au navigateur. Elle ne quitte le serveur sous aucune forme."
note ""
note "  Gardez-la dans le presse-papier : l etape suivante la colle dans Render."
pause "Cle service_role copiee ?"

# --------------------------------------------------------------- 4. Render
stage "Render : poser les deux variables"
say "Ces variables sont declarees `sync: false` dans render.yaml, donc elles ne"
say "seront JAMAIS provisionnees automatiquement. La saisie manuelle est la"
say "seule voie — c est un piege documente dans CLAUDE.md."
open_url "https://dashboard.render.com/web/srv-d9stdnvavr4c73f6ns6g/env"
step "Cliquez « Add Environment Variable », deux fois :"
note ""
if [[ -n "${SUPABASE_URL}" ]]; then
  note "    SUPABASE_URL         = ${SUPABASE_URL}"
else
  note "    SUPABASE_URL         = (l URL de projet copiee a l etape 2)"
fi
note "    SUPABASE_SERVICE_KEY = (la cle service_role copiee a l etape 3)"
note ""
note "  SUPABASE_BUCKET porte deja « medias » via le blueprint : ne rien faire."
step "Enregistrez."
warn "Enregistrer declenche un redeploiement : l API redemarre."
pause "Les deux variables sont enregistrees ?"

# --------------------------------------------------------- 5. verification
stage "Verifier que le mode simule a disparu"
say "On attend que l API reponde de nouveau, puis on controle."
printf "  "
for _ in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w '%{http_code}' https://bledigo-api.onrender.com/health || true)
  [[ "$code" == "200" ]] && break
  printf "."
  sleep 5
done
printf "\n"
if [[ "${code:-}" == "200" ]]; then
  printf "  %s/health repond 200%s\n" "$GREEN" "$RESET"
else
  warn "L API ne repond pas encore. Le redeploiement prend parfois 3 minutes."
fi
say ""
say "Le controle qui compte se lit dans les journaux :"
open_url "https://dashboard.render.com/web/srv-d9stdnvavr4c73f6ns6g/logs"
step "Cherchez « MediaService » dans les journaux du dernier demarrage."
note "  AVANT  : « SUPABASE_URL ou SUPABASE_SERVICE_KEY absent : ... mode simule »"
note "  APRES  : cette ligne ne doit PLUS apparaitre. Son absence est le signal."
say ""
step "Preuve finale : ajoutez une photo a une annonce, rechargez la page"
say  "  completement, et verifiez que l image revient depuis supabase.co et non"
say  "  depuis picsum.photos."

finish
